POST http://localhost:3001/recipes
Content-Type: application/json

{
    "title": "Spinach Crepeshes",
    "ingredients": "'2 eggs', '5 dl milk', '2.5 dl flour', '1 bag of frozen spinach', '1 tbs of salt'",
    "image": "https://is.mediadelivery.fi/img/658/aaf82930112c45c7ba566334e85f786b.jpg.webp",
    "season": "all year" 
}